export const newData = [
    {
        name: 'BITGAMES',
        interval: 'R/P24H',
        payment: 'Directly',
        url: 'http://9m.no/ꝲ㼃',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'CLAIMBTC',
        interval: 'R/P24H',
        payment: 'Directly',
        url: 'http://9m.no/ⴄ𖣊',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'BITRAFFLES',
        interval: 'R/P24H',
        payment: 'Directly',
        url: 'http://9m.no/ヴ魥',
        security: 'ReCaptcha',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'BESTCHANGE',
        interval: 'R/P30M',
        payment: 'Directly',
        url: 'http://9m.no/ᡤ꩞',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'AUTTO',
        interval: 'R/P60M',
        payment: 'Directly',
        url: 'http://9m.no/ﱂ㌸',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'GITCOIN',
        interval: 'R/P5M',
        payment: 'Directly',
        url: 'http://9m.no/⳽퐌',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'MINEBITCOIN',
        interval: 'R/P20M',
        payment: 'Directly',
        url: 'http://9m.no/䞦ᬦ',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'BTCSOURCE',
        interval: 'R/P20M',
        payment: 'Xapo',
        url: 'http://9m.no/诸妦',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'WBIT',
        interval: 'Continuous',
        payment: 'Xapo',
        url: 'http://9m.no/𒆯୰',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'MAGICBITCOIN',
        interval: 'R/P5M',
        payment: 'Directly',
        url: 'http://9m.no/𑖕ℒ',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'BITCOINALIENS',
        interval: 'R/P5M',
        payment: 'Directly',
        url: 'http://9m.no/垽畔',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'FREEBITBOX',
        interval: 'R/P2M',
        payment: 'FaucetBox',
        url: 'http://9m.no/➀鑴',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'BTCFREEBIES',
        interval: 'R/P2M',
        payment: 'FaucetBox',
        url: 'http://9m.no/𓍍ክ',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'BITCOINS43',
        interval: 'R/P720M',
        payment: 'FaucetBox',
        url: 'http://9m.no/쑼鈜',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }, {
        name: 'DOGSFAUCET',
        interval: 'R/P120M',
        payment: 'Directly',
        url: 'http://9m.no/九𑣗',
        security: 'NaN',
        payout: 'NaN',
        cashout: 'NaN',
        coin: 'Bitcoin'
    }
  ];
